apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-curl-pod
spec:
  podSelector:
    matchLabels:
      app: curl-pod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: target-pod
      ports:
        - protocol: TCP
          port: 8880
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: 32000
          endPort: 32768
    - to:
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53


#kubectl apply -f networkpolicy.yaml --namespace=testns
