#kubectl apply -f k8s-simple-demo.yaml
#kubectl delete -f k8s-simple-demo.yaml
#kubectl delete ns nsabc
#kubectl create namespace nsabc
#kubectl apply -f k8s-simple-demo.yaml --namespace=nsabc
#kubectl delete -f k8s-simple-demo.yaml
#kubectl delete namespace nsabc
#kubectl -n nsabc describe pod k8s-simple-demo
#kubectl -n nsabc get pod -w
#kubectl -n nsabc logs k8s-simple-demo
#kubectl -n nsabc exec -it k8s-simple-demo -- bash
#kubectl -n nsabc exec -it k8s-simple-demo -- /bin/sh
#kubectl -n nsabc port-forward k8s-simple-demo 30080:80
#kubectl explain pod --recursive | grep -i maxRetries
#kubectl -n nsabc logs -f $(kubectl -n nsabc get pods --field-selector status.phase=Running --no-headers -o custom-columns=":metadata.name" | grep simple-demo-web | head -1)

apiVersion: v1
kind: Namespace
metadata:
  name: nsabc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-demo-web
  namespace: nsabc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-demo-web
  template:
    metadata:
      labels:
        app: simple-demo-web
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        runAsUser: 8888
        runAsGroup: 9999
        fsGroup: 9999
      containers:
        - name: simple-demo-web
          image: simple-demo:v202311171855
          ports:
            - containerPort: 8880
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8880
            initialDelaySeconds: 180
            periodSeconds: 60
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /app/conf
              name: conf-volume
            - mountPath: /app/log
              name: log-volume
            - mountPath: /app/ignorefolder/h2
              name: h2-volume
            - mountPath: /app/upload-folder
              name: upload-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: conf-volume
          emptyDir: {}
        - name: log-volume
          emptyDir: {}
        - name: h2-volume
          emptyDir: {}
        - name: upload-volume
          emptyDir: {}
      restartPolicy: Always

---
#Not to create this service you can use this port-forward command instead.
#kubectl -n nsabc port-forward simple-demo-web-67c84789b9-brbm8 30080:8880
apiVersion: v1
kind: Service
metadata:
  name: simple-demo-service
  namespace: nsabc
  labels:
    app: simple-demo-web
spec:
  ports:
    - port: 8880 # between containers for service call for K8s
      targetPort: 8880 # container port
      nodePort: 30080 # by default >30000 for external call
  type: NodePort
  selector:
    app: simple-demo-web


