apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace definition
namespace: nsaaa

# Deployment definition
resources:
  - ns.yaml
  - pod.yaml
  - nwp.yaml
  - svc.yaml

# Service definition
#services:
#  - svc.yaml