#Not to create this service you can use this port-forward command instead.
#kubectl -n nsaaa port-forward $(kubectl -n nsaaa get pods --field-selector status.phase=Running --no-headers -o custom-columns=":metadata.name" | grep myapp3 | head -1) 30087:80
apiVersion: v1
kind: Service
metadata:
  name: myapp3-service
  namespace: nsaaa
  labels:
    app: myapp3-service
spec:
  ports:
    - port: 80 # between containers for service call for K8s
      targetPort: 80 # container port
      nodePort: 30087 # by default >30000 for external call
  type: NodePort
  selector:
    app: myapp3
